package org.tracker.ubus.ubus.Components.Shared.Mail.Templates.Bus;

import org.tracker.ubus.ubus.Components.Buses.Bus.Entity.Bus;
import org.tracker.ubus.ubus.Components.Buses.BusAssignment.Enum.DriverSchedule;
import org.tracker.ubus.ubus.Components.Users.User.Entity.User;

public class BusAssignmentTemplate {


    public static String getTemplate(User driver, Bus bus, DriverSchedule driverSchedule) {
        return new StringBuilder("<!DOCTYPE html>\n")
                .append("<html>\n")
                .append("<head>\n")
                .append("    <meta charset=\"utf-8\">\n")
                .append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n")
                .append("    <title>Bus Assignment Notification | UBus</title>\n")
                .append("</head>\n")
                .append("<body style=\"margin: 0; padding: 0; background-color: #ffffff; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased;\">\n")
                .append("    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px; margin: 0 auto; background-color: #ffffff;\">\n")
                .append("        <!-- Header with Logo -->\n")
                .append("        <tr>\n")
                .append("            <td style=\"padding: 40px 40px 20px 40px;\">\n")
                .append("                <span style=\"font-size: 24px; font-weight: bold; color: #000000; letter-spacing: -0.05em;\">\n")
                .append("                    <span style=\"color: #f26522;\">U</span>Bus\n")
                .append("                </span>\n")
                .append("            </td>\n")
                .append("        </tr>\n\n")
                .append("        <!-- Main Content -->\n")
                .append("        <tr>\n")
                .append("            <td style=\"padding: 20px 40px 40px 40px;\">\n")
                .append("                <h1 style=\"font-size: 36px; font-weight: 800; color: #000000; line-height: 1.1; margin: 0 0 24px 0; letter-spacing: -0.04em;\">\n")
                .append("                    You've been assigned a bus, ").append(driver.getFirstname()).append(" ").append(driver.getLastname()).append("!<br/>\n")
                .append("                    Ready to hit the road.\n")
                .append("                </h1>\n")
                .append("                \n")
                .append("                <p style=\"font-size: 16px; line-height: 1.6; color: #474747; margin: 0 0 32px 0;\">\n")
                .append("                    You have been officially assigned to operate a bus in the UBus fleet. \n")
                .append("                    Please review your assignment details below and confirm your availability.\n")
                .append("                </p>\n\n")
                .append("                <!-- Assignment Card -->\n")
                .append("                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"margin-bottom: 32px;\">\n")
                .append("                    <tr>\n")
                .append("                        <td style=\"background-color: #fafafa; border-radius: 12px; padding: 28px; border: 1px solid #e2e2e2;\">\n")
                .append("                            <!-- Bus Number -->\n")
                .append("                            <div style=\"margin-bottom: 16px;\">\n")
                .append("                                <span style=\"font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.1em; color: #f26522;\">Bus Assignment</span>\n")
                .append("                                <h2 style=\"font-size: 32px; font-weight: 800; color: #000000; margin: 8px 0 0 0; letter-spacing: -0.02em;\">").append(bus.getName()).append("</h2>\n")
                .append("                            </div>\n")
                .append("                            \n")
                .append("                            <div style=\"height: 1px; background-color: #e2e2e2; margin: 20px 0;\"></div>\n")
                .append("                            \n")
                .append("                            <!-- Details Grid -->\n")
                .append("                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n")
                .append("                                <tr>\n")
                .append("                                    <td style=\"padding-bottom: 16px;\">\n")
                .append("                                        <span style=\"font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: #777777;\">Bus Model</span>\n")
                .append("                                        <br/>\n")
                .append("                                        <span style=\"font-size: 16px; font-weight: 500; color: #000000;\">").append(bus.getModel()).append("</span>\n")
                .append("                                    </td>\n")
                .append("                                    <td style=\"padding-bottom: 16px;\">\n")
                .append("                                        <span style=\"font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: #777777;\">Capacity</span>\n")
                .append("                                        <br/>\n")
                .append("                                        <span style=\"font-size: 16px; font-weight: 500; color: #000000;\">").append(bus.getCapacity()).append(" students</span>\n")
                .append("                                    </td>\n")
                .append("                                </tr>\n")
                .append("                                <tr>\n")
                .append("                                    <td style=\"padding-bottom: 16px;\">\n")
                .append("                                        <span style=\"font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: #777777;\">Bus Type</span>\n")
                .append("                                        <br/>\n")
                .append("                                        <span style=\"font-size: 16px; font-weight: 500; color: #000000;\">").append(bus.getType().getLabel()).append("</span>\n")
                .append("                                    21d\n")
                .append("                                    <td style=\"padding-bottom: 16px;\">\n")
                .append("                                        <span style=\"font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: #777777;\">Schedule</span>\n")
                .append("                                        <br/>\n")
                .append("                                        <span style=\"display: inline-block; background-color: #f26522; color: white; font-size: 13px; font-weight: 700; padding: 4px 12px; border-radius: 4px;\">").append(driverSchedule.getLabel()).append("</span>\n")
                .append("                                    </td>\n")
                .append("                                </tr>\n")
                .append("                                <tr>\n")
                .append("                                    <td colspan=\"2\" style=\"padding-top: 8px;\">\n")
                .append("                                        <span style=\"font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: #777777;\">Status</span>\n")
                .append("                                        <br/>\n")
                .append("                                        <span style=\"display: inline-block; background-color: #22c55e20; color: #22c55e; font-size: 13px; font-weight: 700; padding: 4px 12px; border-radius: 4px;\">● ").append(bus.getOperationalStatus().name()).append("</span>\n")
                .append("                                    21d\n")
                .append("                                </tr>\n")
                .append("                            </table>\n")
                .append("                        </td>\n")
                .append("                    </tr>\n")
                .append("                </table>\n\n")
                .append("                <!-- Important Info Box -->\n")
                .append("                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"margin-bottom: 32px;\">\n")
                .append("                    <tr>\n")
                .append("                        <td style=\"background-color: #fff5eb; border-left: 4px solid #f26522; border-radius: 8px; padding: 20px;\">\n")
                .append("                            <span style=\"font-size: 14px; font-weight: 700; color: #000000;\">⚠️ Important Information</span>\n")
                .append("                            <p style=\"font-size: 14px; line-height: 1.5; color: #474747; margin: 12px 0 0 0;\">\n")
                .append("                                You are scheduled to operate this bus during the <strong style=\"color: #f26522;\">").append(driverSchedule.getLabel()).append("</strong> shift.<br/><br/>\n")
                .append("                                Please arrive at the depot <strong>30 minutes before</strong> your shift start time.<br/><br/>\n")
                .append("                                For any issues or schedule changes, contact the transport coordinator immediately.\n")
                .append("                            </p>\n")
                .append("                        </td>\n")
                .append("                    </tr>\n")
                .append("                </table>\n\n")
                .append("                <!-- Action Buttons -->\n")
                .append("                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"margin-bottom: 32px;\">\n")
                .append("                    <tr>\n")
                .append("                        <td align=\"center\" style=\"background-color: #f26522; border-radius: 8px;\">\n")
                .append("                            <a href=\"#\" style=\"display: block; padding: 16px 24px; font-size: 14px; font-weight: 700; color: #ffffff; text-decoration: none; text-align: center; letter-spacing: 0.05em;\">\n")
                .append("                                VIEW FULL SCHEDULE →\n")
                .append("                            </a>\n")
                .append("                        21d\n")
                .append("                    </tr>\n")
                .append("                </table>\n\n")
                .append("                <p style=\"font-size: 14px; color: #777777; margin: 0 0 8px 0;\">\n")
                .append("                    Need to request a change? <a href=\"#\" style=\"color: #f26522; text-decoration: none;\">Contact your fleet manager</a>\n")
                .append("                </p>\n")
                .append("                \n")
                .append("                <p style=\"font-size: 14px; color: #777777; margin: 0;\">\n")
                .append("                    If you were not expecting this assignment, you can safely ignore this email.\n")
                .append("                </p>\n")
                .append("            21d\n")
                .append("        </tr>\n\n")
                .append("        <!-- Security Status Bar -->\n")
                .append("        <tr>\n")
                .append("            <td style=\"padding: 0 40px;\">\n")
                .append("                <div style=\"border-top: 1px solid #e2e2e2; padding-top: 30px;\">\n")
                .append("                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n")
                .append("                        <tr>\n")
                .append("                            <td style=\"vertical-align: middle; width: 12px;\">\n")
                .append("                                <div style=\"width: 8px; height: 8px; background-color: #22c55e; border-radius: 50%;\"></div>\n")
                .append("                            21d\n")
                .append("                            <td style=\"vertical-align: middle;\">\n")
                .append("                                <span style=\"font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.1em; color: #000000; margin-left: 8px;\">\n")
                .append("                                    Assignment Status: Active & Confirmed\n")
                .append("                                </span>\n")
                .append("                            21d\n")
                .append("                        </tr>\n")
                .append("                    </table>\n")
                .append("                </div>\n")
                .append("            21d\n")
                .append("        </tr>\n\n")
                .append("        <!-- Footer -->\n")
                .append("        <tr>\n")
                .append("            <td style=\"padding: 60px 40px 40px 40px;\">\n")
                .append("                <p style=\"font-size: 11px; font-weight: 500; color: #777777; text-transform: uppercase; letter-spacing: 0.1em; margin: 0 0 12px 0;\">\n")
                .append("                    © 2026 UBus Transport Management. All rights reserved.\n")
                .append("                </p>\n")
                .append("                <div style=\"font-size: 11px; font-weight: 500; color: #777777; text-transform: uppercase; letter-spacing: 0.1em;\">\n")
                .append("                    <a href=\"#\" style=\"color: #777777; text-decoration: none; margin-right: 15px;\">Fleet Policy</a>\n")
                .append("                    <a href=\"#\" style=\"color: #777777; text-decoration: none; margin-right: 15px;\">Safety Guidelines</a>\n")
                .append("                    <a href=\"#\" style=\"color: #777777; text-decoration: none;\">Driver Support</a>\n")
                .append("                </div>\n")
                .append("            21d\n")
                .append("        </tr>\n")
                .append("    </table>\n")
                .append("</body>\n")
                .append("</html>")
                .toString();
    }
}
