spring.application.name=UBUS
server.port=8050


# ============================
# thread
# ============================
spring.threads.virtual.enabled=true


# ==================================
# POSTGRESQL DATABASE CONFIGURATION
# ==================================
#spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?user=postgres.nushixcxagakiwdvmgmm&password=[QKqWsMW9OAUUlDbt]
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
# Credentials as separate properties
spring.datasource.username=postgres.nushixcxagakiwdvmgmm
spring.datasource.password=QKqWsMW9OAUUlDbt
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================================
# JPA / HIBERNATE SETTINGS
# ==================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PgBouncer (Supabase transaction pooler) compatibility
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=true

# ==================================
# CONNECTION POOL (Hikari)
# ==================================
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000


# ===========================
# Jwt Settings
# ===========================
jwt.secret=${JWT_SECRET}
jwt.duration=${JWT_DURATION}


# ==================
# Email Settings
# ==================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${NOTIFICATION_EMAIL}
spring.mail.password=${NOTIFICATION_EMAIL_PASSWORD}
spring.mail.protocol=smtp

spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# =================
# opt duration
# =================
OTP_DURATION_MINUTES=10
otp.durationDurationMinutes=${OTP_DURATION_MINUTES}
otp.length=${OTP_LENGTH}
otp.numeric=${OTP_NUMERIC}
otp.alphabets=${OTP_ALPHABETS}


# =========================
# Spring Security Settings
# =========================
logging.level.org.springframework.security=TRACE