package org.tracker.ubus.ubus.Components.Shared.Mail.Templates;

public final class OtpTemplate {

    public static String otpEmailTemplate(String personName, String otp, int expiryMinutes) {

        System.err.println("Expiry in " + expiryMinutes + " minutes");
        return new StringBuilder("<!DOCTYPE html>\n")
                .append("<html>\n")
                .append("<head>\n")
                .append("    <meta charset=\"utf-8\">\n")
                .append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n")
                .append("    <title>Verify your UBus account</title>\n")
                .append("</head>\n")
                .append("<body style=\"margin: 0; padding: 0; background-color: #ffffff; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased;\">\n")
                .append("    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px; margin: 0 auto; background-color: #ffffff;\">\n")
                .append("        <tr>\n")
                .append("            <td style=\"padding: 40px 40px 20px 40px;\">\n")
                .append("                <span style=\"font-size: 24px; font-weight: bold; color: #000000; letter-spacing: -0.05em;\">\n")
                .append("                    <span style=\"color: #f26522;\">U</span>Bus\n")
                .append("                </span>\n")
                .append("            </td>\n")
                .append("        </tr>\n")
                .append("\n")
                .append("        <tr>\n")
                .append("            <td style=\"padding: 20px 40px 40px 40px;\">\n")
                .append("                <h1 style=\"font-size: 36px; font-weight: 800; color: #000000; line-height: 1.1; margin: 0 0 24px 0; letter-spacing: -0.04em;\">\n")
                .append("                    Hi ").append(personName).append(",<br/>Verify your email to start riding.\n")
                .append("                </h1>\n")
                .append("                <p style=\"font-size: 16px; line-height: 1.6; color: #474747; margin: 0 0 32px 0;\">\n")
                .append("                    To complete your registration at the transit hub, enter the following code on the sign-up screen.\n")
                .append("                </p>\n")
                .append("\n")
                .append("                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n")
                .append("                    <tr>\n")
                .append("                        <td align=\"left\" style=\"background-color: #e2e2e2; border-radius: 4px; padding: 24px; text-align: center;\">\n")
                .append("                            <span style=\"font-size: 42px; font-weight: 800; color: #000000; letter-spacing: 0.2em; font-family: 'Courier New', Courier, monospace;\">\n")
                .append("                                ").append(otp).append("\n")
                .append("                            </span>\n")
                .append("                        </td>\n")
                .append("                    </tr>\n")
                .append("                </table>\n")
                .append("\n")
                .append("                <p style=\"font-size: 14px; color: #777777; margin: 32px 0 0 0;\">\n")
                .append("                    This code will expire in ").append(expiryMinutes).append(" minutes. If you didn't request this, you can safely ignore this email.\n")
                .append("                </p>\n")
                .append("            </td>\n")
                .append("        </tr>\n")
                .append("\n")
                .append("        <tr>\n")
                .append("            <td style=\"padding: 0 40px;\">\n")
                .append("                <div style=\"border-top: 1px solid #e2e2e2; padding-top: 30px;\">\n")
                .append("                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n")
                .append("                        <tr>\n")
                .append("                            <td style=\"vertical-align: middle; width: 12px;\">\n")
                .append("                                <div style=\"width: 8px; height: 8px; background-color: #f26522; border-radius: 50%;\"></div>\n")
                .append("                            </td>\n")
                .append("                            <td>\n")
                .append("                                <span style=\"font-size: 10px; font-weight: 600; text-transform: uppercase; tracking: 0.1em; color: #000000; margin-left: 8px;\">\n")
                .append("                                    Security Status: Active Verification\n")
                .append("                                </span>\n")
                .append("                            </td>\n")
                .append("                        </tr>\n")
                .append("                    </table>\n")
                .append("                </div>\n")
                .append("            </td>\n")
                .append("        </tr>\n")
                .append("\n")
                .append("        <tr>\n")
                .append("            <td style=\"padding: 60px 40px 40px 40px;\">\n")
                .append("                <p style=\"font-size: 11px; font-weight: 500; color: #777777; text-transform: uppercase; letter-spacing: 0.1em; margin: 0 0 12px 0;\">\n")
                .append("                    © 2026 UBus. All rights reserved.\n")
                .append("                </p>\n")
                .append("                <div style=\"font-size: 11px; font-weight: 500; color: #777777; text-transform: uppercase; letter-spacing: 0.1em;\">\n")
                .append("                    <a href=\"#\" style=\"color: #777777; text-decoration: none; margin-right: 15px;\">Privacy</a>\n")
                .append("                    <a href=\"#\" style=\"color: #777777; text-decoration: none; margin-right: 15px;\">Terms</a>\n")
                .append("                    <a href=\"#\" style=\"color: #777777; text-decoration: none;\">Contact</a>\n")
                .append("                </div>\n")
                .append("            </td>\n")
                .append("        </tr>\n")
                .append("    </table>\n")
                .append("</body>\n")
                .append("</html>").toString();
    }

}


